In [22]:
import numpy as npy

# square of the number greater than 50 and cube of the numbers less than 50

arr = npy.random.randint(1, 100, size=(4, 4))

def new_array(arr):
  new_arr = npy.zeros_like(arr)
  for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
      if arr[i, j] > 50:
        new_arr[i, j] = arr[i, j] ** 2
      else:
        new_arr[i, j] = arr[i, j] ** 3
  return new_arr

new_arr = new_array(arr)
print("\n")
print("Previous Array:\n", arr)
print("\nNew Array values :\n", new_arr)



Previous Array:
 [[74 54 32  7]
 [72 67 88  3]
 [64 37  7 54]
 [74 85 39 76]]

New Array values :
 [[ 5476  2916 32768   343]
 [ 5184  4489  7744    27]
 [ 4096 50653   343  2916]
 [ 5476  7225 59319  5776]]


In [23]:
arr = npy.random.randint(1, 21, size=(5, 5))
print("Original array:\n")
print(arr)

#sum of array element greater than 10 and sum of element less than 10

def row_wise_cond_agg(arr):
  result = []
  for row in arr:
    sum_greater_10 = npy.sum(row[row > 10])
    sum_less_equal_10 = npy.sum(row[row <= 10])
    result.append([sum_greater_10, sum_less_equal_10])
  return npy.array(result)

result = row_wise_cond_agg(arr)

print("\nResult:\n", result)


Original array:

[[ 6 10 17 17  1]
 [19 11 19  1  9]
 [18  6  2 16 17]
 [ 7  7  4 14 18]
 [10 18 12  3  9]]

Result:
 [[34 17]
 [49 10]
 [51  8]
 [32 18]
 [30 22]]


In [24]:
arr = npy.random.randint(1, 51, size=(3, 3))
print("Previous array:\n", arr)
print(arr)

#average of elements greater than 25 and average of elements less than or equal to 25

sum_g_25 = 0
sum_l_equal_25 = 0
count_g_25 = 0
count_l_equal_25 = 0
for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    if arr[i, j] > 25:
      sum_g_25 += arr[i, j]
      count_g_25 += 1
    elif arr[i, j] <= 25:
      sum_l_equal_25 += arr[i, j]
      count_l_equal_25 += 1

if count_g_25 > 0:
  avg_greater_25 = sum_g_25 / count_g_25
else:
  avg_g_25 = 0

if count_l_equal_25 > 0:
  avg_less_equal_25 = sum_l_equal_25 / count_l_equal_25
else:
  avg_less_equal_25 = 0

print("\nAverage of elements greater than 25:", avg_greater_25)
print("Average of elements less than or equal to 25:", avg_less_equal_25)


Previous array:
 [[13 37 17]
 [39 38 44]
 [13 31 23]]
[[13 37 17]
 [39 38 44]
 [13 31 23]]

Average of elements greater than 25: 37.8
Average of elements less than or equal to 25: 16.5


In [25]:
#sales sheet

products_list = ["Product one", "Product two", "Product three", "Product four", "Product five"]

units_sold = npy.random.randint(1, 20, size=len(products_list))

unit_prices = npy.random.uniform(10, 50, size=len(products_list))

total = units_sold * unit_prices

sales_sheet = {
    "Product": products_list,
    "Units Sold": units_sold,
    "Unit Price": unit_prices,
    "Total Sales": total
}

print(sales_sheet)
for key, values in sales_sheet.items():
  print("\n")
  print(f"{key}: {values}")


{'Product': ['Product one', 'Product two', 'Product three', 'Product four', 'Product five'], 'Units Sold': array([13,  3, 15,  8,  2]), 'Unit Price': array([30.1779468 , 38.52326534, 11.08469221, 34.91141717, 27.59071553]), 'Total Sales': array([392.31330834, 115.56979601, 166.27038322, 279.29133736,
        55.18143107])}


Product: ['Product one', 'Product two', 'Product three', 'Product four', 'Product five']


Units Sold: [13  3 15  8  2]


Unit Price: [30.1779468  38.52326534 11.08469221 34.91141717 27.59071553]


Total Sales: [392.31330834 115.56979601 166.27038322 279.29133736  55.18143107]


In [26]:
#factorial using while loop
#from 1 to the nth number(inputted number)

def factorial(n):
  if n < 0:
    return "Not for negative numbers."
  elif n == 0:
    return 1
  else:
    value = 1
    i = 1
    while i <= n:
      value *= i
      i += 1
    return value

while True:
  try:
    number = int(input("Enter a positive integer: "))
    if number >= 0:
      break
    else:
      print("Please enter a positive integer.")
  except ValueError:
    print("Invalid input. Please enter an integer.")

fact_values = npy.array([factorial(i) for i in range(1, number + 1)])

print("Factorial values from 1 to", number, ":", fact_values)
print("\n")


Enter a positive integer: 13
Factorial values from 1 to 13 : [         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 6227020800]




In [27]:
#give the prime number till the inputted nth number

def num_prime(n):
  if n <= 1:
    return False
  if n <= 3:
    return True
  if n % 2 == 0 or n % 3 == 0:
    return False
  i = 5
  while i * i <= n:
    if n % i == 0 or n % (i + 2) == 0:
      return False
    i += 6
  return True

def gen_primes(limit):
  primes = []
  for number in range(2, limit + 1):
    if num_prime(number):
      primes.append(number)
  return npy.array(primes)

nth = int(input("Enter the nth num "))
prime_numbers = gen_primes(nth)
print("Prime numbers up to", nth, "are:\n", prime_numbers)


Enter the nth num 10
Prime numbers up to 10 are:
 [2 3 5 7]
